### ISSUE TITLE
Create writeup for Game Center Integration

### ISSUE THREAD

**Issue by Aklaran** [Aklaran/iOS-Project#6]

**Comment by Aklaran** [comment]
Made a lil write up in the wiki - moving to Under Review

https://github.com/Aklaran/iOS-Project/wiki/Game-Center-Integration

Super incomplete (esp. with regards to specific implementation details for leaderboards and achievement), but Game Center is gonna be something we tackle towards the end. Main thing is we need to be ready to connect to iTunes Connect to store player data remotely.

**Comment by mjkern** [comment]
Added some additional information when researching data use and offline caching
